## This script generates snapshots of species' trait distributions and
## time series plots of their densities, traits, and niche overlap /
## competitive differences. It is Figure 1 in the manuscript.

source("./functions.R") ## for integrating the ODEs
require(cowplot) ## for joining and labeling plots in a grid
theme_set(theme_bw()) ## set default theme
theme_update(panel.grid.major=element_blank(), panel.grid.minor=element_blank())


## Make a plot of the trait distributions at some given moment
## Input:
## - dat: data generated by the function organize_results()
## - lab: label to put on the plot
## - moment: at which time point should the community state be plotted
## Output:
## - a ggplot2 plot
plot_snapshot <- function(dat, lab, moment=0) {
  sp <- dat %>% pull(species) %>% unique %>% as.character
  traitaxis <- seq(-1.1, 1.1, l=501) ## sampling the trait axis
  snap <- dat %>% filter(time==moment) %>% select(-time) ## time = moment
  traits <- expand_grid(species=sp, trait=traitaxis) ## data frame with traits
  traits["density"] <- 0 ## add column for population densities
  for (i in sp) {
    v <- snap %>% filter(species==i) %>% select(n, m, sigma)
    traits$density[(traits$species==i)] <- v$n * ## trait normally distributed,
      dnorm(traits$trait[(traits$species==i)], v$m, v$sigma) ## times density
  }
  landscape <- tibble(trait=traitaxis, r=0) ## for plotting intrinsic rates
  landscape$r <- 1-landscape$trait^2/dat$theta[1]^2
  landscape$r[landscape$r<0] <- NA
  landscape$r <- landscape$r*max(traits$density)
  ggplot(traits) + ## generate plot
    geom_line(aes(x=trait, y=density, colour=species), na.rm=TRUE) +
    geom_ribbon(aes(x=trait, ymin=0, ymax=density, fill=species), alpha=0.15) +
    geom_line(data=landscape, aes(x=trait, y=r), linetype="dashed",
              colour="#999999", alpha=0.75, na.rm=TRUE) +
    annotate(geom="text", label=lab, x=-1.1, y=1.01*max(traits$density),
             fontface="bold") +
    ggtitle(paste0("time = ", moment)) +
    scale_x_continuous(name="trait value", limits=c(-1.1, 1.1)) +
    scale_y_continuous(name="density", limits=c(0, NA)) +
    scale_colour_manual(values=c("#0072B2", "#E69F00"), guide=FALSE) +
    scale_fill_manual(values=c("#0072B2", "#E69F00"), guide=FALSE) %>%
    return
}


w <- 0.1 ## competition width
theta <- 1 ## width of intrinsic growth function
K <- c(1.15, 1) ## vector of intrinsic growth potentials
sigma <- c(0.3, 0.3) ## vector of species trait standard deviations
h2 <- c(0.5, 0.5) ## heritability
params <- list(w=w, theta=theta,  K=K, sigma=sigma, h2=h2)
ninit <- c(1, 1) ## initial densities
muinit <- c(-0.01, 0.09) ## initial trait means
ic <- c(ninit, muinit) ## initial conditions coerced into a vector

tmax <- 100 ## time to integrate equations for
stepout <- tmax/150 ## time step size for output
time <- seq(0, tmax, by=stepout) ## sampling points in time

sol <- ode(func=eqs, y=ic, parms=params, times=time) %>% ## solve ODEs
  organize_results(params) ## put results in tidy table
rk <- rhokappa(sol, params) ## get rho and kappa ratio through time


## create plot of species' density distributions at time 0
snapshot1 <- plot_snapshot(sol, "A", 0)

## create plot of species' density distributions at time tmax
snapshot2 <- plot_snapshot(sol, "B", tmax)

## create plot of species densities through time
densplot <- ggplot(sol) +
  geom_line(aes(x=time, y=n, colour=as.factor(species))) +
  scale_y_continuous(name="pop. density", limits=c(0, NA)) +
  scale_colour_manual(values=c("#0072B2", "#E69F00")) +
  annotate(geom="text", label="C", x=0, y=5.2, fontface="bold") +
  theme(legend.position="none")

## create plot of species traits through time
traitplot <- ggplot(sol) +
  geom_ribbon(aes(x=time, ymin=m-sigma, ymax=m+sigma,
                  fill=as.factor(species)), alpha=0.15) +
  geom_line(aes(x=time, y=m, colour=as.factor(species))) +
  ylab("trait value") +
  scale_colour_manual(values=c("#0072B2", "#E69F00")) +
  scale_fill_manual(values=c("#0072B2", "#E69F00")) +
  annotate(geom="text", label="D", x=0, y=0.70, fontface="bold") +
  theme(legend.position="none")

## create plot of niche overlap and competitive difference through time
rkplot <- rk %>%
  rename(`niche overlap`=rho, `competitive difference`=kapparatio) %>%
  gather(quantity, value, c(`niche overlap`, `competitive difference`)) %>%
  ggplot() +
  aes(x=time, y=value, colour=quantity) +
  geom_line() +
  scale_colour_manual(values=c("#0072B2", "#E69F00")) +
  annotate(geom="text", label="E", x=0, y=1.47, fontface="bold") +
  guides(colour=guide_legend(keyheight=0.9)) +
  theme(legend.title=element_blank(), legend.position=c(0.59, 0.52))

## arrange the five sub-plots in a grid
plot_grid(
  snapshot1, snapshot2,
  plot_grid(densplot, traitplot, rkplot, ncol=1),
  nrow=1
)
